import type { Metadata } from "next";
import "./globals.css";
import { ModalProvider, QueryProvider, ToastProivder } from "./providers";
import { ClerkProvider } from "@clerk/nextjs";

export const metadata: Metadata = {
	title: "Dasboard Tasks",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<ClerkProvider>
			<html lang="en">
				<body suppressHydrationWarning={false}>
					<QueryProvider>
						<ToastProivder />
						<div className="h-full w-full overflow-hidden">
							<ModalProvider>{children}</ModalProvider>
						</div>
					</QueryProvider>
				</body>
			</html>
		</ClerkProvider>
	);
}
