import type { Metadata } from "next";
import "./globals.css";
import { ModalProvider, QueryProvider } from "./providers";
import { ClerkProvider } from "@clerk/nextjs";
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

export const metadata: Metadata = {
  title: "Dasboard Tasks",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body suppressHydrationWarning={true} >
          <ModalProvider />
          <ToastContainer />
          <QueryProvider>
            <div className="h-full w-full overflow-hidden">
              {children}
            </div>
          </QueryProvider>
        </body>
      </html >
    </ClerkProvider>
  );
}
